-- return {
--   "Bekaboo/dropbar.nvim",
--   event = "VeryLazy",
--   keys = { { "<leader>wp", function() require("dropbar.api").pick() end, desc = "winbar: pick" } },
--   init = function()
--     highlight.plugin("DropBar", {
--       { DropBarIconUISeparator = { link = "Delimiter" } },
--       { DropBarMenuNormalFloat = { inherit = "Pmenu" } },
--     })
--   end,
--   config = {
--     general = {
--       update_interval = 100,
--       enable = function(buf, win)
--         local b, w = vim.bo[buf], vim.wo[win]
--         local decor = ui.decorations.get({ ft = b.ft, bt = b.bt, setting = "winbar" })
--         return decor.ft ~= false
--             and decor.bt ~= false
--             and b.bt == ""
--             and not w.diff
--             and not api.nvim_win_get_config(win).zindex
--             and api.nvim_buf_get_name(buf) ~= ""
--       end,
--     },
--     icons = {
--       ui = { bar = { separator = " " .. ui.icons.misc.arrow_right .. " " } },
--       kinds = { symbols = vim.tbl_map(function(value) return value .. " " end, lspkind.symbol_map) },
--     },
--     menu = {
--       win_configs = {
--         border = "shadow",
--         col = function(menu) return menu.prev_menu and menu.prev_menu._win_configs.width + 1 or 0 end,
--       },
--     },
--   },
-- }
--
return {}
