return {
  { "catppuccin/nvim",                  lazy = true },
  { "projekt0n/github-nvim-theme",      lazy = true },
  { "kaiuri/nvim-juliana",              lazy = true },
  { "AhmedAbdulrahman/vim-aylin",       lazy = true },
  { "catppuccin/nvim",                  lazy = true },
  { "bluz71/vim-moonfly-colors",        lazy = true },
  { "bluz71/vim-nightfly-colors",       lazy = true },
  { "wuelnerdotexe/vim-enfocado",       lazy = true },
  { "ellisonleao/gruvbox.nvim",         lazy = true },
  { "rebelot/kanagawa.nvim",            lazy = true },
  { "arturgoms/moonbow.nvim",           lazy = true },
  { "rebelot/kanagawa.nvim",            lazy = true },
  { "uloco/bluloco.nvim",               lazy = true },
  { "tanvirtin/monokai.nvim",           lazy = true },
  { "loctvl842/monokai-pro.nvim",       lazy = true },
  { "EdenEast/nightfox.nvim",           lazy = true },
  { "shaunsingh/nord.nvim",             lazy = true },
  { "navarasu/onedark.nvim",            lazy = true },
  { "olimorris/onedarkpro.nvim",        lazy = true },
  { "nyoom-engineering/oxocarbon.nvim", lazy = true },
  { "rose-pine/neovim",                 lazy = true },
  { "tiagovla/tokyodark.nvim",          lazy = true },
  {
    "mcchrish/zenbones.nvim",
    lazy = true,
    dependencies = "rktjmp/lush.nvim",
  },
}
